### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [awillrich/ioBroker.hiorgserver#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/awillrich/ioBroker.hiorgserver

- [ ] [E112] extIcon must be the same as an icon but with github path
- [ ] [E125] External icon not found under URL: https://raw.githubusercontent.com/awillrich/ioBroker.hiorgserver/master/admin/hiorgserver.png
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.hiorgserver"
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E500] node_modules found in repo. Please delete it
- [ ] [E503] "iob_npm.done" found in repo! Please add it to .gitignore
- [ ] [E801] No repository about text found. Please go to "https://github.com/awillrich/ioBroker.hiorgserver", press the first "Edit" button you will find on the page and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/awillrich/ioBroker.hiorgserver" and press "Manage topics"
- [ ] [E818] file iob_npm.done found in repository, but not found in .npmignore

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "hiorgserver" in latest repository
- [ ] [E901] .gitignore not found

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by awillrich** [comment]
fixed
